export { connect, makeClientLayer, protocolLayer, protocolLayerWithRecovery, AcnClientTag } from "./protocol"
export type { AcnClient } from "./protocol"

export {
  AcnInstanceManager,
  AcnEnsureRequestSchema,
  AcnEnsureEventSchema,
  AcnReadyInstanceSchema,
  RemoteAcnEnsureMessageSchema,
  runAcnEnsure,
  type AcnEnsureRequest,
  type AcnEnsureEvent,
  type AcnInstance,
  type RemoteAcnEnsureMessage,
} from "./acn-jit/acn-instance-manager"
export {
  makeLocalAcnInstanceManager,
  type LocalAcnInstanceManagerOptions,
  type AcnLaunchOverride,
} from "./acn-jit/local-acn-instance-manager"
export {
  ChildProcessSpawner,
  scopeAcnCandidate,
  type SpawnedAcnCandidate,
} from "./acn-jit/child-process"
export { BunDetachedChildProcessSpawner } from "./acn-jit/bun-spawn-process"
export {
  makeRemoteAcnInstanceManager,
  RemoteAcnErrorResponseSchema,
} from "./acn-jit/remote-acn-instance-manager"
export {
  makeAcnJitRuntime,
  type AcnStartup,
  type AcnClientCloseReport,
  type AcnClientCloseResult,
  type AcnJitRuntime,
} from "./acn-jit/acn-recovering-client"
export {
  AcnLifecycleStateSchema,
  AcnLifecycleObservationSchema,
  AcnStartingPhaseSchema,
  AcnFailureStageSchema,
  type AcnLifecycle,
  type AcnLifecycleState,
  type AcnStartingPhase,
  type AcnInstallationPhase,
  type AcnFailureStage,
  type AcnStartupProgress,
} from "./acn-jit/lifecycle"

export { TracingLayer, makeTracingLayer, type MakeTracingLayerOptions } from "./tracing"

export {
  DisplayState as DisplayStateSchema,
  DisplayTimeline as DisplayTimelineSchema,
  DisplayViewSnapshot,
  DisplayViewShape as DisplayViewShapeSchema,
  MagnitudeRpcs,
  StreamEvent as StreamEventSchema,
  canonicalExtensionForImageMediaType,
  filenameWithImageExtension,
  forkIdToKey,
  imageMediaTypeFromFilename,
  imageMediaTypeFromMime,
  isSupportedImageFilename,
  ProviderModelCatalogLifecycle,
  ProviderModelCatalogLoading,
  ProviderModelCatalogReady,
  ProviderModelCatalogRefreshing,
  ProviderModelCatalogDegraded,
  ProviderModelCatalogUnavailable,
  ModelSlotUnassigned,
  ModelSlotConfiguredRemote,
  ModelSlotConfiguredLocal,
  SlotIdSchema,
  LocalInferenceAcceleratorIdSchema,
  LocalInferenceMemoryDomainIdSchema,
  PercentageSchema,
  ModelCapabilitiesSchema,
  ModelFailureSchema,
  ProviderModelCatalogStateSchema,
  ProviderCatalogEntrySchema,
  ProviderModelCatalogEntrySchema,
  SlotSelectionSchema,
  ModelSlotDescriptorSchema,
  ModelSlotAvailabilitySchema,
  ModelLoadPlanSchema,
  ModelSlotInstanceLifecycleSchema,
  ModelSlotInstanceSchema,
  ModelSlotActionSchema,
  ModelSlotSchema,
  LocalInferenceAcceleratorSchema,
  LocalInferenceMemoryDomainSchema,
  ModelSlotsStateSchema,
  LocalInferenceHardwareSchema,
  PRIMARY_SLOT_ID,
  SECONDARY_SLOT_ID,
  MODEL_SLOT_IDS,
  ProviderModelCatalogMirror,
  ModelSlotsMirror,
  LocalInferenceHardwareMirror,
  LocalModelsMirror,
  OnboardingMirror,
  ModelOfferingTargetIdSchema,
  DownloadAttemptIdSchema,
  ModelServingConfigurationIdSchema,
  ModelInstanceIdSchema,
  RecommendationIdSchema,
  ModelAssessmentIdSchema,
  AssessmentEnvironmentIdSchema,
  LocalModelsStateSchema,
} from "@magnitudedev/acn-protocol"

export type {
  DownloadAttemptId,
  ModelOfferingTargetId,
  RecommendationId,
  LocalModel,
  LocalModelRecommendation,
  LocalModelsState,
  AgentCommunicationMessage,
  RawClipboardImageAttachment,
  CreateSessionInitial,
  DisplayActor,
  DisplayRootStatus,
  DisplayWorkerStatus,
  DisplayActivity,
  DisplayAttachment,
  DisplayMessage,
  DisplayState,
  DisplayTasks,
  DisplayTimeline,
  DisplayTimelineEntry,
  DisplayTimelinePresentation,
  DisplayTimelinePresentationMode,
  DisplayTimelineStatusSlot,
  DisplayTimelineWindowShape,
  DisplayTimelineWindowInfo,
  DisplayViewShape,
  DisplayMessageTimelineEntry,
  DisplayToolSummaryTimelineEntry,
  DisplayToolStepTimelineEntry,
  DirectoryCandidate,
  ErrorDisplayMessage,
  RawFileImageAttachment,
  RawImageAttachment,
  RawMentionOccurrence,
  ImageAttachment,
  ImageMediaType,
  InterruptedMessage,
  ListSessionsResult,
  MentionCandidate,
  MentionAttachment,
  MentionDirectoryAttachment,
  MentionFileAttachment,
  MentionFileRangeAttachment,
  MentionContentType,
  MentionLineRange,
  MessageAttachment,
  PendingInboundCommunication,
  SearchDirectoriesResult,
  SearchMentionsResult,
  SessionCwdSummary,
  SessionMetadata,
  SessionOptions,
  StreamEvent,
  TaskAssignee,
  TaskDisplayRow,
  TimelineActivity,
  ToolMessage,
  ToolStepPresentation,
  ToolSummaryPresentation,
  ToolPhase,
  ToolTone,
  ToolIcon,
  ToolDiffHunk,
  ToolDiffSlot,
  ToolFileRef,
  ToolSummaryDetailItem,
  ShellPresentation,
  FileWritePresentation,
  FileEditPresentation,
  FileReadPresentation,
  FileSearchPresentation,
  FileTreePresentation,
  FileViewPresentation,
  WebSearchPresentation,
  WebFetchPresentation,
  SkillPresentation,
  CheckpointPresentation,
  SpawnWorkerPresentation,
  GenericToolPresentation,
  QueryImagePresentation,
} from "@magnitudedev/acn-protocol"
export type * from "@magnitudedev/acn-protocol"

export { createRoles, isRoleId, ROLE_IDS, ROLE_TO_SLOT, DEFAULT_REASONING_EFFORT, SLOT_IDS, SLOT_DISPLAY_NAMES, SLOT_DESCRIPTIONS } from "@magnitudedev/roles"
export type { RoleId } from "@magnitudedev/roles"

export { resolveBinaryCommand, defaultBinaryPath, defaultDataDir, type ResolveBinaryOptions, type ResolvedBinaryCommand } from "./binary"
export { SDK_VERSION, SDK_REVISION, SDK_ACN_TARGET } from "./version"
export {
  AcnAdministrationFailed,
  AcnEnsuranceFailed,
  BinaryNotFound,
  BinaryRevisionMismatch,
  BinaryVersionMismatch,
  DownloadFailed,
  ChecksumMismatch,
  AcnEnsuranceError,
  type StreamDisplayViewFailure,
  type WatchFileFailure,
} from "./errors"

export { isEnvFlagOn } from "@magnitudedev/utils"
export { normalizeReferencedPath } from "./path-utils"

// =============================================================================
// Provider client surface — the sole provider boundary for agent & ACN
// =============================================================================

export {
  ProviderClient,
  createProviderClient,
  type ProviderClientShape,
  type ProviderClientConfig,
  type ProviderRegistryInfo,
  type ProviderRuntimeConfig,
  type ProviderCatalogOutcome,
  type ProviderRejection,
  type ProviderClientError,
  type BaseCallOptions,
  type ModelDiscoveryOperationId,
  type ModelPropertyDiscoveryError,
  type ModelPropertyDiscoveryRequest,
  type ModelPropertyName,
  type ReasoningEffort,
  type ProviderModelBindOptions,
  type ProviderModel,
  type ProviderModelAvailability,
  type ProviderModelDisabledReason,
  type ProviderId,
  type ProviderModelId,
  type ModelFamilyId,
  AVAILABLE_PROVIDER_MODEL,
  isProviderModelAvailable,
  ModelCatalogError,
  ProviderIdSchema,
  ProviderModelIdSchema,
  ModelFamilyIdSchema,
  ProviderModelAvailabilitySchema,
  ProviderModelSchema,
  ModelDiscoveryOperationIdSchema,
  ModelPropertyDiscoveryErrorSchema,
  ModelPropertyDiscoveryRequestSchema,
  ModelPropertyNameSchema,
  ReasoningEffortSchema,
  ReasoningProperty,
  VisionProperty,
  type MagnitudeModelInfo,
  type MagnitudeCallOptions,
  type MagnitudeAdditionalOptions,
  type WebSearchResult,
  type WebSearchError,
  type WebSearchSource,
  WebSearchSourceSchema,
  formatWebSearchError,
  type UsageQuery,
  type CloudUsageResponse,
  type FetchUsageOptions,
  type UsagePeriod,
  makeFileBackedModelCatalog,
  createMagnitudeCompatibleSpec,
  MagnitudeModelListResponseSchema,
  toMagnitudeModelInfo,
  classifyMagnitudeRejectedResponse,
  classifyModelFamilyFromEvidence,
  tryParseErrorBody,
  type ParsedMagnitudeApiError,
} from "./provider-client"

export {
  type ToolCallId,
  type ChatCompletionsStreamChunk,
  type StreamFailure,
  type StreamStartFailure,
  type Prompt,
  type ToolDefinition,
  StreamOperationalFailure,
  StreamProviderError,
  StreamProviderCorrectnessViolation,
  StreamClientCorrectnessViolation,
  StreamStartClientCorrectnessViolation,
  StreamStartProviderCorrectnessViolation,
  StreamStartProviderRejection,
  StreamStartOperationalFailure,
  acceptedHttpResponse,
  payloadSample,
  rejectedHttpResponse,
  streamStartFailureFromRejectedResponse,
  toCauseInfo,
  nativeChatCompletionsCodec,
} from "@magnitudedev/ai"
