//! Safe access to llama.cpp's higher-level `common/sampling` policy.
//!
//! Unlike [`crate::sampling`], this module does not require callers to reproduce
//! llama.cpp's sampler-chain construction. It preserves the pinned upstream
//! defaults and model sampling metadata, then applies only explicitly configured
//! overrides.

use std::borrow::Borrow;
use std::ffi::{c_char, CStr, CString, NulError};
use std::ptr::{self, NonNull};
use std::string::FromUtf8Error;

use llama_cpp_sys_2 as sys;

use crate::context::LlamaContext;
use crate::model::LlamaModel;
use crate::token::LlamaToken;

const NULL_TOKEN: sys::llama_token = -1;

/// A sampler-chain component, in application order.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommonSamplerType {
    /// Don't Repeat Yourself sequence penalty.
    Dry,
    /// Keep the highest-scoring `k` candidates.
    TopK,
    /// Nucleus sampling.
    TopP,
    /// Minimum-probability sampling.
    MinP,
    /// Locally typical sampling.
    TypicalP,
    /// Static or dynamic temperature.
    Temperature,
    /// Exclude Top Choices sampling.
    Xtc,
    /// Fill-in-the-middle sampling.
    Infill,
    /// Repeat, frequency, and presence penalties.
    Penalties,
    /// Top-n-sigma filtering.
    TopNSigma,
    /// Adaptive probability selection. When present, this selects the token in
    /// place of llama.cpp's normal distribution sampler.
    AdaptiveP,
}

impl CommonSamplerType {
    fn raw(self) -> sys::llama_rs_common_sampler_type {
        match self {
            Self::Dry => sys::LLAMA_RS_COMMON_SAMPLER_DRY,
            Self::TopK => sys::LLAMA_RS_COMMON_SAMPLER_TOP_K,
            Self::TopP => sys::LLAMA_RS_COMMON_SAMPLER_TOP_P,
            Self::MinP => sys::LLAMA_RS_COMMON_SAMPLER_MIN_P,
            Self::TypicalP => sys::LLAMA_RS_COMMON_SAMPLER_TYPICAL_P,
            Self::Temperature => sys::LLAMA_RS_COMMON_SAMPLER_TEMPERATURE,
            Self::Xtc => sys::LLAMA_RS_COMMON_SAMPLER_XTC,
            Self::Infill => sys::LLAMA_RS_COMMON_SAMPLER_INFILL,
            Self::Penalties => sys::LLAMA_RS_COMMON_SAMPLER_PENALTIES,
            Self::TopNSigma => sys::LLAMA_RS_COMMON_SAMPLER_TOP_N_SIGMA,
            Self::AdaptiveP => sys::LLAMA_RS_COMMON_SAMPLER_ADAPTIVE_P,
        }
    }
}

/// Mirostat token-selection mode.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommonMirostat {
    /// Use the configured sampler chain and distribution sampler.
    Disabled,
    /// Mirostat 1.0.
    Version1,
    /// Mirostat 2.0.
    Version2,
}

impl CommonMirostat {
    fn raw(self) -> i32 {
        match self {
            Self::Disabled => 0,
            Self::Version1 => 1,
            Self::Version2 => 2,
        }
    }
}

/// Why a grammar was constructed. llama.cpp uses this to decide whether an
/// assistant generation prefix must be prefilled into the grammar state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommonGrammarKind {
    /// A caller-supplied GBNF grammar.
    User,
    /// A grammar generated from a response JSON Schema.
    OutputFormat,
    /// A grammar generated by the chat template for tool calls.
    ToolCalls,
}

impl CommonGrammarKind {
    fn raw(self) -> sys::llama_rs_common_grammar_type {
        match self {
            Self::User => sys::LLAMA_RS_COMMON_GRAMMAR_USER,
            Self::OutputFormat => sys::LLAMA_RS_COMMON_GRAMMAR_OUTPUT_FORMAT,
            Self::ToolCalls => sys::LLAMA_RS_COMMON_GRAMMAR_TOOL_CALLS,
        }
    }
}

/// A GBNF grammar and its semantic origin.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonGrammar {
    /// Grammar origin.
    pub kind: CommonGrammarKind,
    /// GBNF source rooted at `root`.
    pub source: String,
}

/// A condition that activates a lazy grammar.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CommonGrammarTrigger {
    /// Activate on an already-resolved token identifier.
    Token {
        /// Token identifier.
        token: LlamaToken,
        /// Optional diagnostic representation of the token.
        value: Option<String>,
    },
    /// Activate on a literal word. The native bridge resolves single-token words
    /// to token triggers exactly as llama-server does.
    Word(String),
    /// Activate when this regular expression matches.
    Pattern(String),
    /// Activate only when this regular expression matches the full text.
    PatternFull(String),
}

/// One explicit token-logit adjustment.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CommonLogitBias {
    /// Token identifier.
    pub token: LlamaToken,
    /// Value added to the token logit. Negative infinity forbids the token.
    pub bias: f32,
}

/// Maximum reasoning generated between the configured thinking tags.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReasoningBudgetLimit {
    /// Do not impose a numeric limit. This can still arm runtime control or
    /// suppress a lazy output grammar while the model is thinking.
    Unlimited,
    /// Force the configured ending sequence after this many generated tokens.
    Tokens(u32),
}

/// Configuration for llama.cpp's reasoning-budget sampler.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommonReasoningBudget {
    /// Numeric limit.
    pub limit: ReasoningBudgetLimit,
    /// Token sequence that enters the reasoning block, expressed as text and
    /// tokenized by the pinned model vocabulary.
    pub start_tag: String,
    /// Token sequence that exits the reasoning block.
    pub end_tag: String,
    /// Text inserted before `end_tag` when the limit is exhausted.
    pub forced_message: String,
    /// Keep the sampler armed for an explicit runtime `force_reasoning_end` call.
    pub controllable: bool,
}

/// Explicit overrides for `common_params_sampling`.
///
/// `None` means “use the pinned llama.cpp default,” including supported GGUF
/// sampling metadata. `Some(Vec::new())` explicitly replaces an upstream list
/// with an empty one.
#[derive(Clone, Debug, Default)]
pub struct CommonSamplerConfig {
    /// Random seed.
    pub seed: Option<u32>,
    /// Number of accepted tokens retained for repetition-aware samplers.
    pub history_tokens: Option<i32>,
    /// Number of top probabilities retained for inspection.
    pub probabilities: Option<i32>,
    /// Minimum candidates retained by truncating samplers.
    pub minimum_keep: Option<i32>,
    /// Top-k limit.
    pub top_k: Option<i32>,
    /// Nucleus probability.
    pub top_p: Option<f32>,
    /// Minimum relative probability.
    pub min_p: Option<f32>,
    /// XTC activation probability.
    pub xtc_probability: Option<f32>,
    /// XTC probability threshold.
    pub xtc_threshold: Option<f32>,
    /// Typical-sampling probability.
    pub typical_p: Option<f32>,
    /// Base temperature. Non-positive values produce greedy selection.
    pub temperature: Option<f32>,
    /// Dynamic-temperature range.
    pub dynamic_temperature_range: Option<f32>,
    /// Dynamic-temperature entropy exponent.
    pub dynamic_temperature_exponent: Option<f32>,
    /// Number of recent tokens affected by penalties.
    pub repeat_last_n: Option<i32>,
    /// Repetition penalty.
    pub repeat_penalty: Option<f32>,
    /// Frequency penalty.
    pub frequency_penalty: Option<f32>,
    /// Presence penalty.
    pub presence_penalty: Option<f32>,
    /// DRY penalty multiplier.
    pub dry_multiplier: Option<f32>,
    /// DRY exponential base.
    pub dry_base: Option<f32>,
    /// Repeated length allowed before DRY applies.
    pub dry_allowed_length: Option<i32>,
    /// Number of recent tokens scanned by DRY.
    pub dry_penalty_last_n: Option<i32>,
    /// Adaptive-p target probability.
    pub adaptive_target: Option<f32>,
    /// Adaptive-p exponential moving-average decay.
    pub adaptive_decay: Option<f32>,
    /// Mirostat mode.
    pub mirostat: Option<CommonMirostat>,
    /// Top-n-sigma threshold.
    pub top_n_sigma: Option<f32>,
    /// Mirostat target entropy.
    pub mirostat_tau: Option<f32>,
    /// Mirostat learning rate.
    pub mirostat_eta: Option<f32>,
    /// Prevent every end-of-generation token, matching llama-server's
    /// `ignore_eos` behavior rather than suppressing only one EOS identifier.
    pub ignore_eos: Option<bool>,
    /// Disable sampler performance collection.
    pub no_perf: Option<bool>,
    /// Collect per-token timing when supported by the pinned implementation.
    pub timing_per_token: Option<bool>,
    /// DRY sequence breakers.
    pub dry_sequence_breakers: Option<Vec<String>>,
    /// Ordered sampler components.
    pub samplers: Option<Vec<CommonSamplerType>>,
    /// Optional grammar.
    pub grammar: Option<CommonGrammar>,
    /// Whether grammar activation is deferred until a trigger matches.
    pub grammar_lazy: Option<bool>,
    /// Lazy-grammar triggers.
    pub grammar_triggers: Option<Vec<CommonGrammarTrigger>>,
    /// Special-token strings preserved by lazy grammar. The C++ bridge tokenizes
    /// these with the exact model vocabulary and keeps only single-token values.
    pub preserved_tokens: Option<Vec<String>>,
    /// Explicit logit biases.
    pub logit_bias: Option<Vec<CommonLogitBias>>,
    /// Assistant prefix already rendered into the prompt. Output-format and
    /// tool-call grammars prefill this into their state.
    pub generation_prompt: Option<String>,
    /// Reasoning-budget state machine configuration.
    pub reasoning_budget: Option<CommonReasoningBudget>,
}

/// Sampler-chain performance counters collected by llama.cpp.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct CommonSamplerPerformance {
    /// Time spent inside the primitive sampler chain.
    pub sample_milliseconds: f64,
    /// Number of sampled tokens.
    pub sampled_tokens: i32,
}

/// Failures constructing or operating the common sampler.
#[derive(Debug, thiserror::Error)]
pub enum CommonSamplerError {
    /// A configuration string contains an interior NUL byte.
    #[error("sampler configuration contains an interior NUL byte: {0}")]
    InteriorNul(#[from] NulError),
    /// Native text was not valid UTF-8.
    #[error("llama.cpp returned invalid UTF-8: {0}")]
    InvalidUtf8(#[from] FromUtf8Error),
    /// A token count cannot be represented by the pinned native API.
    #[error("{field} exceeds the native i32 range: {value}")]
    ValueOutOfRange {
        /// Configuration field.
        field: &'static str,
        /// Rejected value.
        value: u32,
    },
    /// llama.cpp rejected an operation.
    #[error("llama.cpp common/sampling failed with status {status}: {message}")]
    Native {
        /// Native status integer.
        status: i32,
        /// Native diagnostic.
        message: String,
    },
    /// Native construction succeeded without returning an owner.
    #[error("llama.cpp returned a null common sampler")]
    NullSampler,
    /// A context from a different model was passed to the sampler.
    #[error("common sampler and inference context belong to different models")]
    MismatchedModel,
    /// The requested output was not produced by the latest successful decode.
    #[error("logits for output index {index} are not available")]
    LogitsUnavailable {
        /// Batch-token index, or negative output-row index, requested by the caller.
        index: i32,
    },
    /// Native description construction succeeded without returning text.
    #[error("llama.cpp returned a null sampler description")]
    NullDescription,
}

/// RAII owner of a `common_sampler` built by the exact pinned llama.cpp revision.
#[derive(Debug)]
pub struct CommonSampler<'model> {
    raw: NonNull<sys::llama_rs_common_sampler>,
    model: &'model LlamaModel,
}

impl<'model> CommonSampler<'model> {
    /// Construct the same high-level sampler chain used by llama.cpp tools.
    ///
    /// # Errors
    ///
    /// Returns an error for invalid strings, out-of-range budgets, invalid
    /// grammar configuration, or native sampler-construction failures.
    pub fn new(
        model: &'model LlamaModel,
        config: &CommonSamplerConfig,
    ) -> Result<Self, CommonSamplerError> {
        let encoded = EncodedConfig::new(config)?;
        let raw_config = encoded.raw();
        let mut raw = ptr::null_mut();
        let mut error = ptr::null_mut();
        let status = unsafe {
            sys::llama_rs_common_sampler_init(
                model.model.as_ptr(),
                &raw const raw_config,
                &raw mut raw,
                &raw mut error,
            )
        };
        check_status(status, error)?;
        let raw = NonNull::new(raw).ok_or(CommonSamplerError::NullSampler)?;
        Ok(Self { raw, model })
    }

    /// Feed a prompt or generated token into sampler history.
    ///
    /// Generated tokens additionally advance grammar and reasoning-budget state.
    ///
    /// # Errors
    ///
    /// Returns an error if a native stateful sampler rejects the token.
    pub fn accept(
        &mut self,
        token: LlamaToken,
        is_generated: bool,
    ) -> Result<(), CommonSamplerError> {
        let mut error = ptr::null_mut();
        let status = unsafe {
            sys::llama_rs_common_sampler_accept(
                self.raw.as_ptr(),
                token.0,
                is_generated,
                &raw mut error,
            )
        };
        check_status(status, error)
    }

    /// Feed all prompt tokens into penalty history without advancing grammar.
    ///
    /// # Errors
    ///
    /// Returns the first native token-acceptance failure.
    pub fn accept_prompt(
        &mut self,
        tokens: impl IntoIterator<Item = impl Borrow<LlamaToken>>,
    ) -> Result<(), CommonSamplerError> {
        for token in tokens {
            self.accept(*token.borrow(), false)?;
        }
        Ok(())
    }

    /// Feed one generated token into every stateful sampler.
    ///
    /// # Errors
    ///
    /// Returns an error if a native stateful sampler rejects the token.
    pub fn accept_generated(&mut self, token: LlamaToken) -> Result<(), CommonSamplerError> {
        self.accept(token, true)
    }

    /// Select, but do not accept, a token from one output of the latest decode.
    ///
    /// Set `grammar_first` when probabilities for all returned candidates must
    /// already satisfy the grammar. The normal `false` path is faster and
    /// resamples only when the selected token violates the grammar.
    ///
    /// # Errors
    ///
    /// Returns an error if native sampling or grammar evaluation fails.
    pub fn sample(
        &mut self,
        context: &LlamaContext<'model>,
        index: i32,
        grammar_first: bool,
    ) -> Result<LlamaToken, CommonSamplerError> {
        if !std::ptr::eq(self.model, context.model) {
            return Err(CommonSamplerError::MismatchedModel);
        }
        if !context.has_initialized_logits(index) {
            return Err(CommonSamplerError::LogitsUnavailable { index });
        }
        let mut token = NULL_TOKEN;
        let mut error = ptr::null_mut();
        let status = unsafe {
            sys::llama_rs_common_sampler_sample(
                self.raw.as_ptr(),
                context.context.as_ptr(),
                index,
                grammar_first,
                &raw mut token,
                &raw mut error,
            )
        };
        check_status(status, error)?;
        Ok(LlamaToken(token))
    }

    /// Verify a speculative draft against multiple outputs from the latest
    /// target decode and advance sampler state through the accepted result.
    ///
    /// `indices` must contain one output index for the sampled continuation
    /// plus one for every draft token. The returned vector therefore always
    /// has at least one token on success.
    pub fn sample_and_accept_n(
        &mut self,
        context: &LlamaContext<'model>,
        indices: &[i32],
        draft: &[LlamaToken],
        grammar_first: bool,
    ) -> Result<Vec<LlamaToken>, CommonSamplerError> {
        if !std::ptr::eq(self.model, context.model) {
            return Err(CommonSamplerError::MismatchedModel);
        }
        if indices.len() != draft.len() + 1 {
            return Err(CommonSamplerError::LogitsUnavailable { index: -1 });
        }
        for &index in indices {
            if !context.has_initialized_logits(index) {
                return Err(CommonSamplerError::LogitsUnavailable { index });
            }
        }
        let raw_draft = draft.iter().map(|token| token.0).collect::<Vec<_>>();
        let mut output = vec![NULL_TOKEN; indices.len()];
        let mut output_len = 0_usize;
        let mut error = ptr::null_mut();
        let status = unsafe {
            sys::llama_rs_common_sampler_sample_and_accept_n(
                self.raw.as_ptr(),
                context.context.as_ptr(),
                indices.as_ptr(),
                indices.len(),
                raw_draft.as_ptr(),
                raw_draft.len(),
                grammar_first,
                output.as_mut_ptr(),
                output.len(),
                &raw mut output_len,
                &raw mut error,
            )
        };
        check_status(status, error)?;
        output.truncate(output_len);
        Ok(output.into_iter().map(LlamaToken).collect())
    }

    /// Reset upstream primitive-sampler and accepted-token history.
    ///
    /// The pinned llama.cpp `common_sampler_reset` does not fully rewind its
    /// standalone grammar and reasoning-budget samplers. Construct a fresh
    /// [`CommonSampler`] for each independent completion.
    ///
    /// # Errors
    ///
    /// Returns an error if the native sampler cannot reset its state.
    pub fn reset(&mut self) -> Result<(), CommonSamplerError> {
        let mut error = ptr::null_mut();
        let status =
            unsafe { sys::llama_rs_common_sampler_reset(self.raw.as_ptr(), &raw mut error) };
        check_status(status, error)
    }

    /// Effective random seed after resolving `LLAMA_DEFAULT_SEED`.
    #[must_use]
    pub fn seed(&self) -> u32 {
        unsafe { sys::llama_rs_common_sampler_seed(self.raw.as_ptr()) }
    }

    /// Force an actively counting reasoning budget to emit its configured end.
    /// Returns `false` when the sampler is absent or not currently counting.
    pub fn force_reasoning_end(&mut self) -> bool {
        unsafe { sys::llama_rs_common_sampler_reasoning_budget_force(self.raw.as_ptr()) }
    }

    /// Most recently accepted token, or `None` before any token is accepted.
    #[must_use]
    pub fn last_token(&self) -> Option<LlamaToken> {
        let token = unsafe { sys::llama_rs_common_sampler_last(self.raw.as_ptr()) };
        (token != NULL_TOKEN).then_some(LlamaToken(token))
    }

    /// Human-readable upstream sampler-chain description.
    ///
    /// # Errors
    ///
    /// Returns an error if llama.cpp cannot allocate or encode the description.
    pub fn description(&self) -> Result<String, CommonSamplerError> {
        let mut description = ptr::null_mut();
        let mut error = ptr::null_mut();
        let status = unsafe {
            sys::llama_rs_common_sampler_description(
                self.raw.as_ptr(),
                &raw mut description,
                &raw mut error,
            )
        };
        check_status(status, error)?;
        take_string(description)?.ok_or(CommonSamplerError::NullDescription)
    }

    /// Read sampler-chain performance counters.
    #[must_use]
    pub fn performance(&self) -> CommonSamplerPerformance {
        let performance = unsafe { sys::llama_rs_common_sampler_perf(self.raw.as_ptr()) };
        CommonSamplerPerformance {
            sample_milliseconds: performance.t_sample_ms,
            sampled_tokens: performance.n_sample,
        }
    }

    /// Reset sampler-chain performance counters without resetting sampler state.
    pub fn reset_performance(&mut self) {
        unsafe { sys::llama_rs_common_sampler_perf_reset(self.raw.as_ptr()) };
    }
}

impl Drop for CommonSampler<'_> {
    fn drop(&mut self) {
        unsafe { sys::llama_rs_common_sampler_free(self.raw.as_ptr()) };
    }
}

struct EncodedTrigger {
    value: Option<CString>,
    kind: sys::llama_rs_common_grammar_trigger_type,
    token: sys::llama_token,
}

impl EncodedTrigger {
    fn new(value: &CommonGrammarTrigger) -> Result<Self, CommonSamplerError> {
        let encoded = match value {
            CommonGrammarTrigger::Token { token, value } => Self {
                value: value.as_deref().map(CString::new).transpose()?,
                kind: sys::LLAMA_RS_COMMON_GRAMMAR_TRIGGER_TOKEN,
                token: token.0,
            },
            CommonGrammarTrigger::Word(value) => Self {
                value: Some(CString::new(value.as_str())?),
                kind: sys::LLAMA_RS_COMMON_GRAMMAR_TRIGGER_WORD,
                token: NULL_TOKEN,
            },
            CommonGrammarTrigger::Pattern(value) => Self {
                value: Some(CString::new(value.as_str())?),
                kind: sys::LLAMA_RS_COMMON_GRAMMAR_TRIGGER_PATTERN,
                token: NULL_TOKEN,
            },
            CommonGrammarTrigger::PatternFull(value) => Self {
                value: Some(CString::new(value.as_str())?),
                kind: sys::LLAMA_RS_COMMON_GRAMMAR_TRIGGER_PATTERN_FULL,
                token: NULL_TOKEN,
            },
        };
        Ok(encoded)
    }

    fn raw(&self) -> sys::llama_rs_common_grammar_trigger_input {
        sys::llama_rs_common_grammar_trigger_input {
            type_: self.kind,
            value: option_string_ptr(self.value.as_ref()),
            token: self.token,
        }
    }
}

struct EncodedReasoningBudget {
    tokens: i32,
    start_tag: CString,
    end_tag: CString,
    message: CString,
    controllable: bool,
}

impl EncodedReasoningBudget {
    fn new(value: &CommonReasoningBudget) -> Result<Self, CommonSamplerError> {
        let tokens = match value.limit {
            ReasoningBudgetLimit::Unlimited => -1,
            ReasoningBudgetLimit::Tokens(tokens) => {
                i32::try_from(tokens).map_err(|_| CommonSamplerError::ValueOutOfRange {
                    field: "reasoning budget",
                    value: tokens,
                })?
            }
        };
        Ok(Self {
            tokens,
            start_tag: CString::new(value.start_tag.as_str())?,
            end_tag: CString::new(value.end_tag.as_str())?,
            message: CString::new(value.forced_message.as_str())?,
            controllable: value.controllable,
        })
    }
}

struct EncodedConfig<'a> {
    source: &'a CommonSamplerConfig,
    dry_sequence_breakers: Option<Vec<CString>>,
    dry_sequence_breaker_ptrs: Option<Vec<*const c_char>>,
    samplers: Option<Vec<sys::llama_rs_common_sampler_type>>,
    grammar: Option<CString>,
    grammar_triggers: Option<Vec<EncodedTrigger>>,
    raw_grammar_triggers: Option<Vec<sys::llama_rs_common_grammar_trigger_input>>,
    preserved_tokens: Option<Vec<CString>>,
    preserved_token_ptrs: Option<Vec<*const c_char>>,
    logit_bias: Option<Vec<sys::llama_rs_common_logit_bias_input>>,
    generation_prompt: Option<CString>,
    reasoning_budget: Option<EncodedReasoningBudget>,
}

impl<'a> EncodedConfig<'a> {
    fn new(source: &'a CommonSamplerConfig) -> Result<Self, CommonSamplerError> {
        let dry_sequence_breakers = encode_string_list(source.dry_sequence_breakers.as_deref())?;
        let dry_sequence_breaker_ptrs = string_ptrs(dry_sequence_breakers.as_deref());
        let samplers = source
            .samplers
            .as_ref()
            .map(|values| values.iter().map(|value| value.raw()).collect());
        let grammar = source
            .grammar
            .as_ref()
            .map(|grammar| CString::new(grammar.source.as_str()))
            .transpose()?;
        let grammar_triggers = source
            .grammar_triggers
            .as_ref()
            .map(|values| {
                values
                    .iter()
                    .map(EncodedTrigger::new)
                    .collect::<Result<Vec<_>, _>>()
            })
            .transpose()?;
        let raw_grammar_triggers = grammar_triggers
            .as_ref()
            .map(|values| values.iter().map(EncodedTrigger::raw).collect());
        let preserved_tokens = encode_string_list(source.preserved_tokens.as_deref())?;
        let preserved_token_ptrs = string_ptrs(preserved_tokens.as_deref());
        let logit_bias = source.logit_bias.as_ref().map(|values| {
            values
                .iter()
                .map(|value| sys::llama_rs_common_logit_bias_input {
                    token: value.token.0,
                    bias: value.bias,
                })
                .collect()
        });
        let generation_prompt = source
            .generation_prompt
            .as_deref()
            .map(CString::new)
            .transpose()?;
        let reasoning_budget = source
            .reasoning_budget
            .as_ref()
            .map(EncodedReasoningBudget::new)
            .transpose()?;
        Ok(Self {
            source,
            dry_sequence_breakers,
            dry_sequence_breaker_ptrs,
            samplers,
            grammar,
            grammar_triggers,
            raw_grammar_triggers,
            preserved_tokens,
            preserved_token_ptrs,
            logit_bias,
            generation_prompt,
            reasoning_budget,
        })
    }

    #[allow(clippy::too_many_lines)]
    fn raw(&self) -> sys::llama_rs_common_sampler_config {
        let source = self.source;
        sys::llama_rs_common_sampler_config {
            seed_set: source.seed.is_some(),
            seed: source.seed.unwrap_or_default(),
            n_prev_set: source.history_tokens.is_some(),
            n_prev: source.history_tokens.unwrap_or_default(),
            n_probs_set: source.probabilities.is_some(),
            n_probs: source.probabilities.unwrap_or_default(),
            min_keep_set: source.minimum_keep.is_some(),
            min_keep: source.minimum_keep.unwrap_or_default(),
            top_k_set: source.top_k.is_some(),
            top_k: source.top_k.unwrap_or_default(),
            top_p_set: source.top_p.is_some(),
            top_p: source.top_p.unwrap_or_default(),
            min_p_set: source.min_p.is_some(),
            min_p: source.min_p.unwrap_or_default(),
            xtc_probability_set: source.xtc_probability.is_some(),
            xtc_probability: source.xtc_probability.unwrap_or_default(),
            xtc_threshold_set: source.xtc_threshold.is_some(),
            xtc_threshold: source.xtc_threshold.unwrap_or_default(),
            typical_p_set: source.typical_p.is_some(),
            typical_p: source.typical_p.unwrap_or_default(),
            temperature_set: source.temperature.is_some(),
            temperature: source.temperature.unwrap_or_default(),
            dynatemp_range_set: source.dynamic_temperature_range.is_some(),
            dynatemp_range: source.dynamic_temperature_range.unwrap_or_default(),
            dynatemp_exponent_set: source.dynamic_temperature_exponent.is_some(),
            dynatemp_exponent: source.dynamic_temperature_exponent.unwrap_or_default(),
            repeat_last_n_set: source.repeat_last_n.is_some(),
            repeat_last_n: source.repeat_last_n.unwrap_or_default(),
            repeat_penalty_set: source.repeat_penalty.is_some(),
            repeat_penalty: source.repeat_penalty.unwrap_or_default(),
            frequency_penalty_set: source.frequency_penalty.is_some(),
            frequency_penalty: source.frequency_penalty.unwrap_or_default(),
            presence_penalty_set: source.presence_penalty.is_some(),
            presence_penalty: source.presence_penalty.unwrap_or_default(),
            dry_multiplier_set: source.dry_multiplier.is_some(),
            dry_multiplier: source.dry_multiplier.unwrap_or_default(),
            dry_base_set: source.dry_base.is_some(),
            dry_base: source.dry_base.unwrap_or_default(),
            dry_allowed_length_set: source.dry_allowed_length.is_some(),
            dry_allowed_length: source.dry_allowed_length.unwrap_or_default(),
            dry_penalty_last_n_set: source.dry_penalty_last_n.is_some(),
            dry_penalty_last_n: source.dry_penalty_last_n.unwrap_or_default(),
            adaptive_target_set: source.adaptive_target.is_some(),
            adaptive_target: source.adaptive_target.unwrap_or_default(),
            adaptive_decay_set: source.adaptive_decay.is_some(),
            adaptive_decay: source.adaptive_decay.unwrap_or_default(),
            mirostat_set: source.mirostat.is_some(),
            mirostat: source.mirostat.map(CommonMirostat::raw).unwrap_or_default(),
            top_n_sigma_set: source.top_n_sigma.is_some(),
            top_n_sigma: source.top_n_sigma.unwrap_or_default(),
            mirostat_tau_set: source.mirostat_tau.is_some(),
            mirostat_tau: source.mirostat_tau.unwrap_or_default(),
            mirostat_eta_set: source.mirostat_eta.is_some(),
            mirostat_eta: source.mirostat_eta.unwrap_or_default(),
            ignore_eos_set: source.ignore_eos.is_some(),
            ignore_eos: source.ignore_eos.unwrap_or_default(),
            no_perf_set: source.no_perf.is_some(),
            no_perf: source.no_perf.unwrap_or_default(),
            timing_per_token_set: source.timing_per_token.is_some(),
            timing_per_token: source.timing_per_token.unwrap_or_default(),
            dry_sequence_breakers_set: self.dry_sequence_breakers.is_some(),
            dry_sequence_breakers: option_slice_ptr(self.dry_sequence_breaker_ptrs.as_deref()),
            dry_sequence_breakers_count: option_slice_len(
                self.dry_sequence_breaker_ptrs.as_deref(),
            ),
            samplers_set: self.samplers.is_some(),
            samplers: option_slice_ptr(self.samplers.as_deref()),
            samplers_count: option_slice_len(self.samplers.as_deref()),
            grammar_set: self.grammar.is_some(),
            grammar_type: source
                .grammar
                .as_ref()
                .map_or(sys::LLAMA_RS_COMMON_GRAMMAR_USER, |value| value.kind.raw()),
            grammar: option_string_ptr(self.grammar.as_ref()),
            grammar_lazy_set: source.grammar_lazy.is_some(),
            grammar_lazy: source.grammar_lazy.unwrap_or_default(),
            grammar_triggers_set: self.grammar_triggers.is_some(),
            grammar_triggers: option_slice_ptr(self.raw_grammar_triggers.as_deref()),
            grammar_triggers_count: option_slice_len(self.raw_grammar_triggers.as_deref()),
            preserved_tokens_set: self.preserved_tokens.is_some(),
            preserved_tokens: option_slice_ptr(self.preserved_token_ptrs.as_deref()),
            preserved_tokens_count: option_slice_len(self.preserved_token_ptrs.as_deref()),
            logit_bias_set: self.logit_bias.is_some(),
            logit_bias: option_slice_ptr(self.logit_bias.as_deref()),
            logit_bias_count: option_slice_len(self.logit_bias.as_deref()),
            generation_prompt_set: self.generation_prompt.is_some(),
            generation_prompt: option_string_ptr(self.generation_prompt.as_ref()),
            reasoning_budget_set: self.reasoning_budget.is_some(),
            reasoning_budget_tokens: self
                .reasoning_budget
                .as_ref()
                .map_or(-1, |value| value.tokens),
            reasoning_budget_start_tag: self
                .reasoning_budget
                .as_ref()
                .map_or(ptr::null(), |value| value.start_tag.as_ptr()),
            reasoning_budget_end_tag: self
                .reasoning_budget
                .as_ref()
                .map_or(ptr::null(), |value| value.end_tag.as_ptr()),
            reasoning_budget_message: self
                .reasoning_budget
                .as_ref()
                .map_or(ptr::null(), |value| value.message.as_ptr()),
            reasoning_control: self
                .reasoning_budget
                .as_ref()
                .is_some_and(|value| value.controllable),
        }
    }
}

fn encode_string_list(values: Option<&[String]>) -> Result<Option<Vec<CString>>, NulError> {
    values
        .map(|values| {
            values
                .iter()
                .map(|value| CString::new(value.as_str()))
                .collect::<Result<Vec<_>, _>>()
        })
        .transpose()
}

fn string_ptrs(values: Option<&[CString]>) -> Option<Vec<*const c_char>> {
    values.map(|values| values.iter().map(|value| value.as_ptr()).collect())
}

fn option_string_ptr(value: Option<&CString>) -> *const c_char {
    value.map_or(ptr::null(), |value| value.as_ptr())
}

fn option_slice_ptr<T>(value: Option<&[T]>) -> *const T {
    value.map_or(ptr::null(), |value| {
        if value.is_empty() {
            ptr::null()
        } else {
            value.as_ptr()
        }
    })
}

fn option_slice_len<T>(value: Option<&[T]>) -> usize {
    value.map_or(0, <[T]>::len)
}

fn check_status(
    status: sys::llama_rs_status,
    error: *mut c_char,
) -> Result<(), CommonSamplerError> {
    let message = take_string(error)?.unwrap_or_else(|| "no native diagnostic".to_string());
    if status == sys::LLAMA_RS_STATUS_OK {
        Ok(())
    } else {
        Err(CommonSamplerError::Native { status, message })
    }
}

fn take_string(value: *mut c_char) -> Result<Option<String>, FromUtf8Error> {
    if value.is_null() {
        return Ok(None);
    }
    let bytes = unsafe { CStr::from_ptr(value) }.to_bytes().to_vec();
    unsafe { sys::llama_rs_string_free(value) };
    String::from_utf8(bytes).map(Some)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reasoning_budget_rejects_values_above_native_range() {
        let config = CommonSamplerConfig {
            reasoning_budget: Some(CommonReasoningBudget {
                limit: ReasoningBudgetLimit::Tokens(u32::MAX),
                start_tag: String::new(),
                end_tag: String::new(),
                forced_message: String::new(),
                controllable: false,
            }),
            ..CommonSamplerConfig::default()
        };
        assert!(matches!(
            EncodedConfig::new(&config),
            Err(CommonSamplerError::ValueOutOfRange { .. })
        ));
    }

    #[test]
    fn configuration_rejects_interior_nul() {
        let config = CommonSamplerConfig {
            dry_sequence_breakers: Some(vec!["bad\0breaker".to_string()]),
            ..CommonSamplerConfig::default()
        };
        assert!(matches!(
            EncodedConfig::new(&config),
            Err(CommonSamplerError::InteriorNul(_))
        ));
    }
}
