import { mkdir, readFile, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const PROJECT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..")
const SOURCE_PACKAGE_JSON = resolve(PROJECT_ROOT, "packages/cli/package.json")
const REVISION_FILE = resolve(PROJECT_ROOT, "packages/version/acn-revision.json")
const OUTPUT_FILE = resolve(PROJECT_ROOT, "packages/version/src/version.generated.ts")
const DEVELOPMENT_COUNTER_FILE = resolve(
  homedir(),
  ".magnitude/acn/development-revision-counter",
)

const isDev = process.argv.includes("--dev")

interface RevisionRecord {
  readonly revision: number
}

const readGitShortHash = (): string => {
  const proc = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"], {
    cwd: PROJECT_ROOT,
    stdout: "pipe",
    stderr: "ignore",
  })
  if (proc.exitCode !== 0) return "unknown"
  return proc.stdout.toString().trim() || "unknown"
}

const developmentVersion = (
  baseVersion: string,
  counter: number,
): string => `${baseVersion}+dev.${readGitShortHash()}.${counter}`

const readRevision = async (): Promise<RevisionRecord> => {
  const value = JSON.parse(await readFile(REVISION_FILE, "utf8")) as Partial<RevisionRecord>
  if (
    !Number.isSafeInteger(value.revision) ||
    value.revision! <= 0
  ) {
    throw new Error("packages/version/acn-revision.json is malformed")
  }
  return { revision: value.revision! }
}

export const nextDevelopmentCounter = async (
  path: string = DEVELOPMENT_COUNTER_FILE,
): Promise<number> => {
  await mkdir(dirname(path), { recursive: true, mode: 0o700 })
  let current = 0
  try {
    current = Number((await readFile(path, "utf8")).trim())
    if (!Number.isSafeInteger(current) || current < 0) {
      throw new Error("The local ACN development revision counter is malformed")
    }
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error
  }
  const next = current + 1
  if (!Number.isSafeInteger(next)) {
    throw new Error("The local ACN development revision counter is exhausted")
  }
  await writeFile(path, `${next}\n`, { mode: 0o600 })
  return next
}

async function main() {
  const packageJson = JSON.parse(await Bun.file(SOURCE_PACKAGE_JSON).text()) as { version?: string }

  if (!packageJson.version) {
    throw new Error(`No version found in ${SOURCE_PACKAGE_JSON}`)
  }

  const allocated = await readRevision()
  const developmentCounter = isDev ? await nextDevelopmentCounter() : undefined
  const version = developmentCounter === undefined
    ? packageJson.version
    : developmentVersion(packageJson.version, developmentCounter)
  const revision = allocated.revision + (developmentCounter ?? 0)
  if (!Number.isSafeInteger(revision)) {
    throw new Error("The generated ACN coordination revision exceeds the safe integer range")
  }

  const contents =
    `// Generated by packages/version/scripts/generate-version.ts\n` +
    `// Source: packages/cli/package.json\n` +
    (developmentCounter === undefined
      ? ""
      : `// Local development counter: ${developmentCounter}\n`) +
    `export const MAGNITUDE_VERSION = ${JSON.stringify(version)}\n` +
    `export const ACN_COORDINATION_REVISION = ${revision}\n`

  await Bun.write(OUTPUT_FILE, contents)
}

if (import.meta.main) await main()
